### ISSUE TITLE
직접 컴파일 해야하나요..?

### ISSUE THREAD

**Issue by nnnlog** [solo5star/SimpleClock#1]
응용 프로그램이 없네요.. 비쥬얼 스투디오에 넣고 컴파일 해야하나요?

**Comment by solo5star** [comment]
소스 코드를 다운로드하신 후 SimpleClock.sln 파일을 더블클릭하면 Visual Studio로 프로젝트를 열 수 있습니다.

빌드->솔루션 빌드(Ctrl+Shift+B)를 실행시키면 SimpleClock-master\SimpleClock\bin\Debug 디렉토리에 .exe파일이 생성됩니다.
결과물을 즉시 확인하려면 Ctrl+F5를 입력하시면 됩니다.

**Comment by nnnlog** [comment]
@solo5star 감사합니다.
```그리고 여담으로 미넷 채팅방과 미넷은 더이상 손 안댈 예정이신가요..?```

**Comment by solo5star** [comment]
아마 앞으로 MCBE 개발은 없을거에요. 따라서 미넷 채팅방은 방치될거같네요😢
미리 말씀드렸어야하는데.. 정말 죄송해요.

**Comment by BuildLike** [comment]
ㅠㅠ UI도 솔로님이 차지 하시지...ㅠㅠ

**Comment by nnnlog** [comment]
@BuildLike 제가 차지해서 죄송하네요 ```ㅋㅋ```

**Comment by BuildLike** [comment]
죄송한데 저도 UI 플러그인 만들었는데요 ㅋㅋㅋ

**Comment by nnnlog** [comment]
@BuildLike 제가 UI 플긴 깃헙에 올린거 세게 50순위 안에 들듯요ㅋ
